GET https://api-eventos-3-w.onrender.com/eventos HTTP/1.1

###
GET https://api-eventos-3-w.onrender.com/eventos/1 HTTP/1.1

###
POST https://api-eventos-3-w.onrender.com/eventos HTTP/1.1
Content-Type: application/json

{
    "titulo": "mis 15",
    "descripcion": "esta es una fiesta con tematica lluvia de sobres",
    "fecha": "2024-05-31",
    "hora": "19:00",
    "ubicacion": "caseta santo domingo",
    "categoria": "15 Años"
}

###
PUT https://api-eventos-3-w.onrender.com/eventos/3 HTTP/1.1
Content-Type: application/json

{
  "year": 1989
}

###
DELETE https://api-eventos-3-w.onrender.com/eventos/1 HTTP/1.1